# This is a basic workflow to help you get started with Actions

name: git_udemy2025042258_workflow

# Controls when the workflow will run
on: workflow_dispatch
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, wereld!!!!"
      - name: Print goodbye
        run: |
          echo "goodbye"
          echo test, and deploy your project.
